apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: hsleeacr.azurecr.io/demo-kafka-producer
    newTag: latest  # This will be dynamically updated
