replicaCount: 2

image:
  repository: "{{ .Values.image.repository }}"
  tag: "{{ .Values.image.tag }}"  # This should be set dynamically by ArgoCD
  pullPolicy: Always

imagePullSecrets:
  - name: acr-secret

service:
  type: NodePort
  port: 80
  targetPort: 8080

env:
  BOOTSTRAP_SERVERS: ""
  KAFKA_USERNAME: ""
  KAFKA_PASSWORD: ""

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: false
