name: Deploy Helm Chart to Kubernetes

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "Docker Image Tag"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Helm repository
        uses: actions/checkout@v3
