name: Deploy Helm Chart to Kubernetes

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "Docker Image Tag"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ArgoCD
        run: |
          argocd app set kafka-producer-app --helm-set image.tag=${{ github.event.inputs.imageTag }}
          argocd app sync kafka-producer-app
