name: Deploy to Kubernetes

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=$(date +%Y%m%d%H%M%S)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kafka-producer-app:$IMAGE_TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/kafka-producer-app:$IMAGE_TAG
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update Helm values file
        run: |
          cat <<EOF > values-overrides.yaml
          image:
            repository: "${{ secrets.DOCKER_USERNAME }}/kafka-producer-app"
            tag: "${{ env.IMAGE_TAG }}"
          env:
            BOOTSTRAP_SERVERS: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
            KAFKA_USERNAME: "${{ secrets.KAFKA_USERNAME }}"
            KAFKA_PASSWORD: "${{ secrets.KAFKA_PASSWORD }}"
          EOF

      - name: Deploy using ArgoCD
        run: |
          argocd app set kafka-producer-app --values values-overrides.yaml --repo https://github.com/${{ github.repository }} --revision main
          argocd app sync kafka-producer-app
